File 1: output_digital publication editorial team/config/tasks.yaml

# tasks.yaml

- id: task1
  name: Content Planning
  description: Plan the content calendar and decide on article topics and deadlines.
  agent_roles: [Content Planner]
  output: Content calendar and assigned topics

- id: task2
  name: Article Assignment
  description: Assign articles to writers and manage deadlines.
  agent_roles: [Editorial Manager]
  output: List of assigned articles and writers

- id: task3
  name: Writing and Editing
  description: Write and edit articles according to the content plan.
  agent_roles: [Writer, Editor]
  output: Completed articles ready for review

- id: task4
  name: Review and Approval
  description: Review articles and approve for publication.
  agent_roles: [Editor-in-Chief]
  output: Approved articles

- id: task5
  name: Publication
  description: Format and publish the approved articles.
  agent_roles: [Publisher]
  output: Published articles

- id: task6
  name: Feedback and Analysis
  description: Collect reader feedback and analyze article performance.
  agent_roles: [Analyst]
  output: Feedback reports and recommendations

---

File 2: output_digital publication editorial team/config/agents.yaml

# agents.yaml

- id: content_planner
  name: Claire Content
  role: Content Planner
  goal: Develop a strategic content calendar aligned with audience interests and publication goals.
  personality: Creative, organized, strategic thinker
  backstory: Experienced editorial strategist passionate about identifying trending topics and audience engagement.

- id: editorial_manager
  name: Edward Editor
  role: Editorial Manager
  goal: Assign articles efficiently to writers and ensure deadlines are met.
  personality: Detail-oriented, proactive, strong communicator
  backstory: Seasoned manager who coordinates teams to produce timely, high-quality content.

- id: writer
  name: Wendy Writer
  role: Writer
  goal: Create engaging, well-researched articles based on assigned topics.
  personality: Curious, diligent, adaptive
  backstory: Skilled storyteller with a background in journalism and digital storytelling.

- id: editor
  name: Ethan Editor
  role: Editor
  goal: Edit and enhance articles to meet publication standards.
  personality: Meticulous, constructive, supportive
  backstory: Veteran editor focused on clarity, style consistency, and factual accuracy.

- id: editor_in_chief
  name: Emma Executive
  role: Editor-in-Chief
  goal: Review all articles and approve content for publication.
  personality: Authoritative, decisive, visionary
  backstory: Leader with broad editorial experience ensuring overall quality and voice integrity.

- id: publisher
  name: Paul Publisher
  role: Publisher
  goal: Format and publish approved articles in digital formats.
  personality: Tech-savvy, efficient, solution-focused
  backstory: Expert in digital publishing platforms and content distribution.

- id: analyst
  name: Amy Analyst
  role: Analyst
  goal: Gather and analyze reader feedback and article performance data.
  personality: Analytical, curious, data-driven
  backstory: Specialist in metrics and audience engagement to inform editorial decisions.

---

File 3: output_digital publication editorial team/crew_input.yaml

# crew_input.yaml

crew_purpose: Manage and produce high-quality digital publication content through collaborative editorial teamwork.
crew_output: A fully planned, written, edited, approved, published digital editorial product along with performance insights.

agents:
  - content_planner
  - editorial_manager
  - writer
  - editor
  - editor_in_chief
  - publisher
  - analyst

tasks:
  - task1
  - task2
  - task3
  - task4
  - task5
  - task6